<Project>
  <PropertyGroup>
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
  </PropertyGroup>
  <ItemGroup>
    <PackageVersion Include="BetterConsoleTables" Version="1.1.3" />
    <PackageVersion Include="CasCap.Api.GooglePhotos" Version="3.1.0" />
    <PackageVersion Include="CasCap.Common.Caching" Version="4.3.10" />
    <PackageVersion Include="CasCap.Common.Testing" Version="4.3.10" />
    <PackageVersion Include="McMaster.Extensions.CommandLineUtils" Version="4.1.1" />
    <PackageVersion Include="McMaster.Extensions.Hosting.CommandLine" Version="4.1.1" />
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="9.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.EnvironmentVariables" Version="9.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="9.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.UserSecrets" Version="9.0.9" />
    <PackageVersion Include="Microsoft.Extensions.Hosting" Version="9.0.9" />
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.0.0" />
    <PackageVersion Include="ShellProgressBar" Version="5.2.0" />
    <PackageVersion Include="SixLabors.ImageSharp" Version="3.1.11" />
    <PackageVersion Include="System.Linq.Async" Version="6.0.3" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="coverlet.msbuild" Version="6.0.4" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5" />
  </ItemGroup>
</Project>