<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <UserSecretsId>255ba51e-c46d-40c4-9420-80d485ea10fe</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" />
    <PackageReference Include="Microsoft.Extensions.Configuration.EnvironmentVariables" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" />
    <PackageReference Include="Microsoft.Testing.Extensions.CodeCoverage" />
    <PackageReference Include="xunit.v3" />
  </ItemGroup>

  <ItemGroup Condition="'$(Configuration)'=='Debug'">
    <ProjectReference Include="..\..\..\CasCap.Common\src\CasCap.Common.Testing\CasCap.Common.Testing.csproj" />
  </ItemGroup>
  <ItemGroup Condition="'$(Configuration)'=='Release'">
    <PackageReference Include="CasCap.Common.Testing" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CasCap.GooglePhotosCli\CasCap.GooglePhotosCli.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="appsettings.Test.json" CopyToOutputDirectory="Always" />
  </ItemGroup>

</Project>
